spring.application.name=teamly

jwt.secret=mysuperduperextremlylongsecretforjwt
jwt.expiration=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/teamly
spring.jpa.hibernate.ddl-auto=update

cloudinary.cloud_name=dnfwhh6bj
cloudinary.api_key=835237556675466
cloudinary.api_secret=-Hyd21jda1P3bg3lzAMzexd41uY
